
# Super simple Makefile because I keep hitting the up arrow key constantly trying to find the right
# cli params

lfq:
	g++ lfq_test.cpp -lpthread -O0 -g -std=c++17

merge:
	g++ merge_sort.cpp -std=c++17 -lpthread -g -O0 -Wpedantic -Wextra -Wall -pg

tps:
	g++ thread_pool_sched.cpp -std=c++17 -lpthread -g -O0 -Wpedantic -Wextra -Wall -pg ../libfunctions.a